reviewpost/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import signupview, loginview, listview, detailview, CreateClass, logoutview, evaluationview

app_name = 'reviewpost'

urlpatterns = [
    path('signup/', signupview, name='signup'),
    path('login/', loginview, name='login'),
    path('list/', listview, name='list'),
    path('detail/<int:pk>/', detailview, name='detail'),
    path('create/', CreateClass.as_view(), name='create'),
    path('logout/', logoutview, name='logout'),
    path('evaluation/<int:pk>', evaluationview, name='evaluation')
]

reviewproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reviewpost.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviewpost/models.py
from django.db import models
from django.contrib.auth.models import User

EVALUATION_CHOICES = [('良い', '良い'),('悪い', '悪い')]
class ReviewModel(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    images = models.ImageField(upload_to='')
    useful_review = models.IntegerField(null=True, blank=True, default=0)
    useful_review_record = models.TextField()
    evaluation = models.CharField(max_length=10, choices = EVALUATION_CHOICES)

reviewpost/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import authenticate, login, logout
from .models import ReviewModel
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

def signupview(request):
    print(request.method)
    if request.method == 'POST':
        username_data = request.POST['username_data']
        password_data = request.POST['password_data']
        try:
            user = User.objects.create_user(username_data, '', password_data)
        except IntegrityError:
            return render(request, 'reviewpost/signup.html', {'error': 'このユーザーは既に登録されています'})
    else:
        print(User.objects.all())
    return render(request, 'reviewpost/signup.html', {})

def loginview(request):
    if request.method == 'POST':
        username_data = request.POST['username_data']
        password_data = request.POST['password_data']
        user = authenticate(request, username=username_data, password=password_data)
        if user is not None:
            login(request, user)
            return redirect('reviewpost:list')
        else:
            return redirect('reviewpost:login')
    return render(request, 'reviewpost/login.html')

@login_required
def listview(request):
    object_list = ReviewModel.objects.all()
    return render(request, 'reviewpost/list.html', {'object_list':object_list})

def detailview(request, pk):
    object = ReviewModel.objects.get(pk=pk)
    return render(request, 'reviewpost/detail.html', {'object':object})

class CreateClass(CreateView):
    template_name = 'reviewpost/create.html'
    model = ReviewModel
    fields = ('title', 'content','author', 'images', 'evaluation')
    success_url = reverse_lazy('reviewpost:list')

def logoutview(request):
    logout(request)
    return redirect('reviewpost:login')

def evaluationview(request, pk):
    post = ReviewModel.objects.get(pk=pk)
    author_name = request.user.get_username() + str(request.user.id)
    if author_name in post.useful_review_record:
        return redirect('reviewpost:list')
    else:
        post.useful_review = post.useful_review + 1
        post.useful_review_record = post.useful_review_record + author_name
        post.save()
        return redirect('reviewpost:list')

reviewpost/templates/reviewpost/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    
{% block header %}
{% endblock header %}

</head>
  <body>

    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

reviewpost/templates/reviewpost/create.html
{% extends 'reviewpost/base.html' %}
{% load static%}

{% block content %}

{% if user.is_authenticated %}
<form action='' method='POST' enctype="multipart/form-data">{% csrf_token %}
<p>タイトル：<input type='text' name='title'></p>
<p>内容：<input type='text' name='content'></p>
<p>画像：<input type='file' name='images'></p>
<p>評価</p>
<select name='evaluation'>
    <option value="良い">良い</option>
    <option value="悪い">悪い</option>
</select>
<input type="hidden" name="author" value="{{ user.id }}">
<input type='submit' value='作成する'>
</form>

{% else %}
ログインしてください
<a href="{% url 'reviewpost:login' %}" class="btn btn-primary" role="button" aria-pressed="true">ログイン</a>
{% endif %}
{% endblock content %}

reviewpost/templates/reviewpost/detail.html
{% extends 'reviewpost/base.html' %}
{% load static %} 

{% block header %}
<link rel='stylesheet' type="text/css" href="{% static 'style.css' %}">
{% endblock header %}

{% block content %}

{{ errormessage }}

<div class='container'>
  <div class="card">
      <h5 class="card-header">{{ object.title }}</h5>
      <div class="card-body">
        <p><img src='{{object.images.url}}' width=300></p>
        <h5 class="card-title">投稿者：{{ object.author }}</h5>
        <h5 class="card-title">レビュー内容：{{ object.content }}</h5>
        <h5 class="card-title">投稿者の評価：{{ object.evaluation }}</h5>
        <h5 class="card-title">レビューが参考になった人：{{ object.useful_review }}人</h5>
        <a href="{% url 'reviewpost:evaluation' object.pk %}" class="btn btn-primary" role="button" aria-pressed="true">参考になった</a>
        <a href="{% url 'reviewpost:list' %}" class="btn btn-primary">戻る</a>
      </div>
    </div>
  </div>
{% endblock content %}

reviewpost/templates/reviewpost/list.html
{% extends 'reviewpost/base.html' %}
{% load static %} 

{% block header %}
{% endblock header %}

{% block content %}
<div class='container'>
  {% for item in object_list %}
  <div class="card">
      <h5 class="card-header">{{ item.title }}</h5>
      <div class="card-body">
        <h5 class="card-title">投稿者：{{ item.author }}</h5>
        <h5 class="card-title">レビューが参考になった人：{{ item.useful_review }}人</h5>
        <a href="{% url 'reviewpost:detail' item.pk %}" class="btn btn-primary">詳しく見る</a>
      </div>
    </div>
  {% endfor %}
  </div>
{% endblock content %}

reviewpost/templates/reviewpost/login.html
{% extends 'reviewpost/base.html' %}
{% load static %}

{% block content%}


<div class="container">
  <form class="form-signin" method='post'>{% csrf_token %}
<img class="mb-4" src="{% static 'reviewpost/bootstraplogo.svg' %}" alt="" width="72" height="72">
<h1 class="h3 mb-3 font-weight-normal">Please login</h1>
<label for="inputEmail" class="sr-only">Username</label>
<input type="text" id="inputEmail" class="form-control" placeholder="username" name="username_data" required autofocus>
<label for="inputPassword" class="sr-only">Password</label>
<input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password_data" required>
<div class="checkbox mb-3">
</div>
<button class="btn btn-lg btn-primary btn-block" type="submit">login</button>
<p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
</form>
</div>
{% endblock content %}

reviewpost/templates/reviewpost/signup.html
{% extends 'reviewpost/base.html' %}
{% load static %}

{% block content%}

  <div class="container">
    <form class="form-signin" method='post'>{% csrf_token %}
  <img class="mb-4" src="{% static 'reviewpost/bootstraplogo.svg' %}" alt="" width="72" height="72">
  <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
  {% if error %}
  {{ error }}
  {% endif %}
  <label for="inputEmail" class="sr-only">Username</label>
  <input type="text" id="inputEmail" class="form-control" placeholder="username" name="username_data" required autofocus>
  <label for="inputPassword" class="sr-only">Password</label>
  <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password_data" required>
  <div class="checkbox mb-3">
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
</form>
</div>
{% endblock content %}